# Generated by Django 4.2.5 on 2023-09-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='del_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='def.png', upload_to='profile_pics/')),
                ('email', models.EmailField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=40)),
                ('religion', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=4)),
                ('date_of_birth', models.DateField()),
                ('is_alive', models.BooleanField(default=False, null=True)),
                ('previous_id', models.IntegerField(default=0)),
            ],
        ),
    ]
